### ISSUE TITLE
Code quality improvements + checklist

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/dash-cc#24]
- [x] Add `luts.py` and move relevant code there
- [x] Remove unused imports everywhere
- [x] Add OpenGraph fragments to application.py
- [x] Clean up string handling code (no regex needed here) etc
